#!/bin/bash 
# Autor: @Fs0usa
# Data de criação/update:  24/04/17
# Objetivo: Adicionar um host ao squid
# Descrição: none
# Projeto: Fechado
# Utilize por sua conta e risco, não modifique o script com o intuito
# de ganhar em cima de tal.

# Tabelas de cores que eu utilizo.
fim="tput sgr0"
bold="tput bold"
vermelho="tput setaf 1"
verde="tput setaf 2"
amarelo="tput setaf 3"
azul="tput setaf 4"
roxo="tput setaf 5"
ciano="tput setaf 6"
branco="tput setaf 7"
limpa="tput setaf 9"
# Inicio do script
clear
# Hostname da máquina
nameuser=`uname -n`
$amarelo ; $bold; echo -e "Bem vindo(a) $nameuser\n"; $branco; $bold
read -p "Host: " host
echo "acl adchost dstdomain .$host\nhttp_access allow adchost" >> /etc/squid*/squid.conf
echo "Aguarde"; $fim
service squid restart &>/dev/null
service squid3 restart &>/dev/null
clear
$verde ; $bold; echo "O host $host foi adicionado com sucesso."; $fim
exit